version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "github-actions"
      - "dependabot"
    schedule:
      interval: "daily"
      time: "04:00"
      timezone: Europe/Rome
    reviewers:
      - "marcolovazzano"
