name: Conventional Commit

on:
  push:
    branches:
      - feat/**
      - main

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.1.1
        with:
          node-version: 'lts/*'

      - name: Install commitlint plugins
        run: |
              npm install --save-dev \
                @commitlint/cli \
                @commitlint/config-conventional

      - name: Validate push commits
        run: |
          npx commitlint --from=HEAD~1 --verbose
